<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE8yvitl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE8yvitl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerE8yvitl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerE8yvitl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerE8yvitl\appProdProjectContainer([
    'container.build_hash' => 'E8yvitl',
    'container.build_id' => '96e034f5',
    'container.build_time' => 1604954340,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE8yvitl');
