<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjekera\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjekera/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXjekera.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXjekera\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXjekera\appProdProjectContainer([
    'container.build_hash' => 'Xjekera',
    'container.build_id' => 'cf90e2c3',
    'container.build_time' => 1609348167,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjekera');
