<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMwwk1vt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMwwk1vt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMwwk1vt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMwwk1vt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMwwk1vt\appProdProjectContainer([
    'container.build_hash' => 'Mwwk1vt',
    'container.build_id' => '916a39ed',
    'container.build_time' => 1605192812,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMwwk1vt');
