<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ7s5xia\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ7s5xia/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJ7s5xia.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJ7s5xia\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJ7s5xia\appDevDebugProjectContainer([
    'container.build_hash' => 'J7s5xia',
    'container.build_id' => '00792fcc',
    'container.build_time' => 1609343546,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ7s5xia');
