<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGs9vrgg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGs9vrgg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGs9vrgg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGs9vrgg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGs9vrgg\appDevDebugProjectContainer([
    'container.build_hash' => 'Gs9vrgg',
    'container.build_id' => '963dbe27',
    'container.build_time' => 1603822195,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGs9vrgg');
