<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTe6tuzs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTe6tuzs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTe6tuzs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTe6tuzs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTe6tuzs\appDevDebugProjectContainer([
    'container.build_hash' => 'Te6tuzs',
    'container.build_id' => 'aa447598',
    'container.build_time' => 1603897298,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTe6tuzs');
